server:
  port: 9002
spring:
  application:
    name: tensquare_recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.89.195.63:3311/tensquare_recruit?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true