server:
  port: 9004
spring:
  application:
    name: tensquare-article
  redis:
    host: 121.89.195.63
    port: 6666
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.89.195.63:3311/tensquare_article?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
## redis key
total:
  like:
    count:
      key: TOTAL:LIKE:COUNT
user:
  like:
    article:
      key: USER:LIKE:ARTICLE
article:
  liked:
    user:
      key: ARTICLE:LIKED:USER

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka